### ISSUE TITLE
Neon summer 2019 overview

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/Neon#332]
- [x] Validate MEI 4.0 files (done in #329)
- [x] Display manuscripts lyrics aligned with neumes (done in #356)
- [x] Design and implement grouping and ungrouping when dealing with syllables, neumes, and neume components (e.g., what will happen with syllables that continue in the next staff? what happens with chants that start or end in the next or previous page?)
  - [x] Grouping/ungrouping #299 (done in #331)
  - [x] Syllables across staves #306
- [x] Use IIIF/DIVA to display images #333
- [x] Implement image rotation and shifting to compensate for slanted lines (done in #481 + skewed staves milestone)
- [x] Implement editing of lyrics #339

**Comment by jacob-hutnyk** [comment]
:)
