### ISSUE TITLE
Use diva.js to display manuscripts and rendered MEI

### ISSUE THREAD

**Issue by JRegimbal** [DDMAL/Neon#333]
Switch to using diva.js to display the manuscripts and the rendered MEI from verovio. The following functionality should be available:

* [x] Neon2 viewer mode using diva.js #337 (viewer appears to be working in 4852a86)
* [x] Neon2 editing features using diva.js #343 
* [x] Change dev server included to just feed an editor page with the Salzinnes manuscript loaded with IIIF and a few MEI files associated with some pages. #340 (dev server supports loading arbitrary MEI files and a manifest in 4852a866)
* [x] User interface for adding files to development server #345

**Comment by JRegimbal** [comment]
Changing since multiple pages are easy.
